name: stac-catalog-builder
channels:
  - conda-forge
dependencies:
  - python=3.11.0
  - click=8.1.*
  - geopandas=0.14.*
  - openeo=0.26.*
  - psutil
  - pyarrow=14.0.*
  - pydantic=2.5.*
  - pyproj=3.6.*
  - pystac[validation]=1.8.*
  - rasterio=1.3.*
  - requests==2.31.*
  - requests-mock==1.11.*
  - rio-stac=0.8.*
  - shapely=2.0.*
  - stac-validator=3.3.*
  - stactools=0.5.*
  - ipykernel
  - jupyter
  - pytest
  - yarl=1.9.*
  - pip
  - pip:
    - --extra-index-url https://artifactory.vgt.vito.be/artifactory/api/pypi/python-packages/simple
    - terracatalogueclient==0.1.14
    - requests_auth==7.0.*
    - dynaconf==3.2.*
